### ISSUE TITLE
Generated flex code won't compile with -pedantic

### ISSUE THREAD

**Issue by bneijt** [bneijt/ccbuild#26]
The current generated flex scanner will not compile with g++-4.7 and the pedantic option:

  yylex.cc:1590:28: error: declaration of ‘int isatty(int)’ has a different exception specifier

Probably have to port the lexer to alternatives, like http://www.flexcpp.org/
